Add Eval to Foundry CLI
mosaicml/llm-foundry pull request #1345
Opened 2024-07-10 19:40 UTC by KuuCi

This PR allows users to call composer llm-foundry eval {YAML_PATH} {ARGS} while maintaining correctness with existing evaluation script. The motivation is for DLE where we want to make the CLI much more intuitive in the docker images

2024-07-11 20:13 UTC, KuuCi commented
Working tests:
test-eval-rdrmLF runs:
`composer -c llmfoundry eval eval/yamls/hf_eval.yaml || (echo "Command failed - killing python" && pkill python && exit 1) `

test-eval-qQI2O7 runs:
`composer -n 8 -c llmfoundry eval eval/yamls/hf_eval.yaml || (echo "Command failed - killing python" && pkill python && exit 1) `

2024-07-11 20:25 UTC, b-chu commented
Is there a better name for the llmfoundry/train folder?

2024-07-11 20:26 UTC, irenedea requested changes
I don't think we should have `llmfoundry.train.eval`. That naming doesn't make sense to me.

2024-07-11 20:41 UTC, b-chu commented
`llmfoundry.train.train` also doesn't seem great

2024-07-16 09:55 UTC, KuuCi commented
Test run too show working:

mcli logs test-eval-9mG0gB:
`composer -n 8 -c llmfoundry eval eval/yamls/hf_eval.yaml || (echo "Command failed - killing python" && pkill python && exit 1)`

mcli logs test-eval-VCcxoX:
`composer eval/eval.py eval/yamls/hf_eval.yaml || (echo "Command failed - killing python" && pkill python && exit 1)`

2024-07-16 19:26 UTC, dakinggg approved these changes

2024-07-16 19:26 UTC, dakinggg commented on tests/a_scripts/eval/test_eval.py
> +from llmfoundry.command_utils import evaluate  # noqa: E402
noqa?

2024-07-16 19:26 UTC, dakinggg commented on tests/a_scripts/eval/test_eval_inputs.py
> +from llmfoundry.command_utils import evaluate  # noqa: E402
noqa?

2024-07-16 19:26 UTC, dakinggg commented on llmfoundry/command_utils/eval.py
> +install()
we removed this from train a while ago. lets remove here too

2024-07-16 20:50 UTC, merged