DRAFT: BERT Migration
mosaicml/llm-foundry pull request #481
Opened 2023-07-21 21:36 UTC by cojennin

**--DRAFT--**
A working branch for @jacobfulano and @cojennin as they migrate BERT into LLM-Foundry

2023-08-29 17:44 UTC, jacobfulano commented
@dakinggg @alextrott16 this PR is ready for review

2023-08-31 00:13 UTC, alextrott16 requested changes
Overall, this looks very solid. I do think some YAMLs got overlooked and need to be updated to reflect how everything is landing here in `llm-foundry`. I think that needs to be addressed before stamping Approve.

Also, please weigh in on the "signature" of the model constructors, ie the config structure that the new BERT model constructors expect. I'm thinking they should be as unified as possible with the existing constructors. If unifying seems dumb, please say so. Or, if it's just out of scope for now, then I'm OK with scoping a refactor into a future PR.

Finally, let's get all the tests/sanity checks cleared before we merge. For the record, the PR summary (which includes that checklist) is absolutely fantastic and is so appreciated by this humble reviewer!

2023-08-31 02:03 UTC, dakinggg reviewed
A couple high level comments. We need tests with this PR and we need documentation with this PR. I suggest a small section of train readme about bert, and a readme in `finetune_bert_glue`

2023-08-31 02:03 UTC, dakinggg commented on scripts/train/yamls/pretrain/mosaicbert-base-uncased.yaml
> +  model_config:
same

2024-02-02 00:18 UTC, dakinggg commented
@cojennin should we close this?

2024-03-06 20:03 UTC, dakinggg commented
Closing as this is not being actively worked on.

2024-03-06 20:03 UTC, closed without merging