Delta to JSONL conversion script cleanup and bug fix
mosaicml/llm-foundry pull request #868
Opened 2024-01-12 19:57 UTC by nancyhung

This change includes 2 primary changes:
1. Fix bug in the Delta to JSONL conversion script where the `runtime_version` of the cluster still had alphabetic characters, which failed version parsing i.e. (`14.0.1-photon` instead of `14.0.1`). This change adds more regex to strip the extra alphabetic characters and trailing delineators (`-`, `.`).
2. Add some cleanups to the script to abstract the cluster validation and details into its own separate function. We also don't need the `cluster_id` argument to be mandatory now that we are supporting `serverless`.

I was able to test this e2e with a yaml generated by the finetuning API that works in the databricks KaaS cluster!
Run name: `test-delta-Udjv3E`

2024-01-12 20:08 UTC, irenedea approved these changes
LGTM

2024-01-12 22:01 UTC, XiaohanZhangCMU requested changes

2024-01-12 22:01 UTC, XiaohanZhangCMU commented on scripts/data_prep/convert_delta_to_json.py
>                      cluster_id=args.cluster_id).getOrCreate()
cluster_id=args.cluster_id).getOrCreate()

2024-01-13 06:53 UTC, XiaohanZhangCMU approved these changes
LGTM

2024-01-13 07:06 UTC, merged